# Generated by Django 4.0.4 on 2022-05-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDealership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(default='second name', max_length=100),
            preserve_default=False,
        ),
    ]
