# Generated by Django 4.0.4 on 2022-05-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarDealership', '0002_rename_full_name_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CarDealership.car'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CarDealership.client'),
        ),
    ]
